In [ ]:
import numpy as np
X = np.array([
    [78, 85, 80, 82],
    [65, 70, 68, 72],
    [90, 92, 88, 91],
    [72, 75, 70, 74],
    [85, 88, 84, 86]
])
print("Original Dataset:\n", X)
mean = np.mean(X, axis=0)
X_centered = X - mean
print("\nMean of each attribute:\n", mean)
print("\nMean Centered Data:\n", X_centered)
cov_matrix = np.cov(X_centered.T)
print("\nCovariance Matrix:\n", cov_matrix)
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
print("\nEigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)
idx = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[idx]
eigenvectors = eigenvectors[:, idx]
print("\nSorted Eigenvalues:\n", eigenvalues)
print("\nSorted Eigenvectors:\n", eigenvectors)
pc1 = eigenvectors[:, 0]
print("\nFirst Principal Component (PC1 Eigenvector):\n", pc1)
pc1_scores = np.dot(X_centered, pc1)
print("\nPC1 Scores for each student:\n", pc1_scores)


Original Dataset:
 [[78 85 80 82]
 [65 70 68 72]
 [90 92 88 91]
 [72 75 70 74]
 [85 88 84 86]]

Mean of each attribute:
 [78. 82. 78. 81.]

Mean Centered Data:
 [[  0.   3.   2.   1.]
 [-13. -12. -10.  -9.]
 [ 12.  10.  10.  10.]
 [ -6.  -7.  -8.  -7.]
 [  7.   6.   6.   5.]]

Covariance Matrix:
 [[99.5 90.  85.  78.5]
 [90.  84.5 79.5 72.5]
 [85.  79.5 76.  69.5]
 [78.5 72.5 69.5 64. ]]

Eigenvalues:
 [3.20458599e+02 2.35286281e+00 7.28078921e-02 1.11572997e+00]

Eigenvectors:
 [[ 0.55281648  0.8150415  -0.17147263  0.02642786]
 [ 0.5110015  -0.26081446  0.28965745 -0.76612783]
 [ 0.48493995 -0.48221894 -0.69394668  0.22524685]
 [ 0.44508949 -0.18747818  0.63650114  0.60134314]]

Sorted Eigenvalues:
 [3.20458599e+02 2.35286281e+00 1.11572997e+00 7.28078921e-02]

Sorted Eigenvectors:
 [[ 0.55281648  0.8150415   0.02642786 -0.17147263]
 [ 0.5110015  -0.26081446 -0.76612783  0.28965745]
 [ 0.48493995 -0.48221894  0.22524685 -0.69394668]
 [ 0.44508949 -0.18747818  0.60134314  0.63650114]]